plugins { id "com.android.application" }

android {
    namespace "kr.song.peugeot.frontoemv16"
    compileSdk 35

    defaultConfig {
        applicationId "kr.song.peugeot.frontoemv16"
        minSdk 21
        targetSdk 27
        versionCode 16
        versionName "16.0-oem-source2"
    }

    buildTypes {
        debug { minifyEnabled false }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
