plugins { id "com.android.application" }

android {
    namespace "kr.song.peugeot.reverseholdv12"
    compileSdk 35

    defaultConfig {
        applicationId "kr.song.peugeot.reverseholdv12"
        minSdk 21
        targetSdk 27
        versionCode 12
        versionName "12.0-source"
    }

    buildTypes {
        debug { minifyEnabled false }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
